# 文件路径：.github/workflows/fetch-preferred-ip.yml
name: 定时更新优选 IP 列表

# 授予 GITHUB_TOKEN 写权限，才能 push 结果到仓库
permissions:
  contents: write  # 控制权限以允许写入仓库内容 0

on:
  schedule:
    - cron: '0 2 * * *'   # 每天 UTC 02:00 运行一次（可根据需要调整） 1
  workflow_dispatch:     # 允许手动触发

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true  # 保留写权限的令牌以便后续 push 2

      - name: 拉取优选 IP 列表并保存
        run: |
          curl --silent https://raw.githubusercontent.com/946727185/auto-ip-update/main/优选ip.txt \
            -o preferred_ips.txt    # 使用 curl 获取内容并输出到 preferred_ips.txt 3

      - name: 提交并推送结果
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add preferred_ips.txt
          git diff --cached --quiet || git commit -m "自动更新优选 IP 列表"
          git push                # 将生成的文件推送回仓库 4
