name: 定时合并 IP 列表

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行一次（北京时间为 08:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 获取并合并 IP 列表
        run: |
          # 定义原始文件链接
          urls=(
            "https://raw.githubusercontent.com/ymyuuu/IPDB/main/BestCF/bestcfv4.txt"
            "https://raw.githubusercontent.com/ymyuuu/IPDB/main/BestCF/bestcfv6.txt"
            "https://raw.githubusercontent.com/946727185/auto-ip-update/main/优选ip.txt"
            "https://raw.githubusercontent.com/camel52zhang/yxip/main/ip.txt"
            "https://raw.githubusercontent.com/lu-lingyun/CloudflareST/main/TLS.txt"
            "https://raw.githubusercontent.com/hubbylei/bestcf/main/bestcf.txt"
          )

          # 创建一个临时文件用于存储合并内容
          temp_file=$(mktemp)

          # 遍历每个 URL，获取内容并追加到临时文件
          for url in "${urls[@]}"; do
            curl -s "$url" >> "$temp_file"
            echo -e "\n" >> "$temp_file"  # 添加换行符分隔不同文件内容
          done

          # 将合并后的内容保存到新的文件
          mv "$temp_file" merged_ips.txt

      - name: 提交合并后的文件
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add merged_ips.txt
          git commit -m "自动合并 IP 列表"
          git push
