name: 定时合并 IP 列表

# 给 GITHUB_TOKEN 分配写权限
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行一次
  workflow_dispatch:    # 允许手动触发

jobs:
  fetch-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: 获取并合并 IP 列表
        run: |
          urls=(
            "https://raw.githubusercontent.com/ymyuuu/IPDB/main/BestCF/bestcfv4.txt"
            "https://raw.githubusercontent.com/ymyuuu/IPDB/main/BestCF/bestcfv6.txt"
            "https://raw.githubusercontent.com/946727185/auto-ip-update/main/优选ip.txt"
            "https://raw.githubusercontent.com/camel52zhang/yxip/main/ip.txt"
            "https://raw.githubusercontent.com/lu-lingyun/CloudflareST/main/TLS.txt"
            "https://raw.githubusercontent.com/hubbylei/bestcf/main/bestcf.txt"
          )

          temp_file=$(mktemp)
          for url in "${urls[@]}"; do
            curl -s "$url" >> "$temp_file"
            echo -e "\n" >> "$temp_file"
          done

          mv "$temp_file" merged_ips.txt

      - name: 提交并推送合并后的文件
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add merged_ips.txt
          git diff --quiet || git commit -m "自动合并 IP 列表"
          git push
